[build]
  # Disable CI mode during install and build so warnings don't fail the build
  command = "node check-env.js && CI=false npm ci --legacy-peer-deps && CI=false npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  # Use Node 18 which matches package requirements
  NODE_VERSION = "18"
  # Disable secrets scanning for Supabase anon keys (they are meant to be public)
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_MARKET_DATA_SUPABASE_ANON_KEY,REACT_APP_SUPABASE_ANON_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://checkout.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co https://*.supabase.in wss://*.supabase.co wss://*.supabase.in https://api.stripe.com https://checkout.stripe.com https://openrouter.ai https://*.twilio.com wss://*.twilio.com https://api.openai.com https://oauth2.googleapis.com https://www.googleapis.com https://accounts.google.com https://gmail.googleapis.com https://speech.googleapis.com https://osbackend-zl1h.onrender.com; frame-src 'self' https://js.stripe.com https://checkout.stripe.com https://accounts.google.com; object-src 'none'; base-uri 'self'; form-action 'self' https://checkout.stripe.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
